# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\spring22\SBEN311\task#3\GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Slider(QtWidgets.QSlider):
    def mousePressEvent(self, event):
        super(Slider, self).mousePressEvent(event)
        if event.button() == QtCore.Qt.LeftButton:
            val = self.pixelPosToRangeValue(event.pos())
            self.setValue(val)

    def pixelPosToRangeValue(self, pos):
        opt = QtWidgets.QStyleOptionSlider()
        self.initStyleOption(opt)
        gr = self.style().subControlRect(QtWidgets.QStyle.CC_Slider, opt, QtWidgets.QStyle.SC_SliderGroove, self)
        sr = self.style().subControlRect(QtWidgets.QStyle.CC_Slider, opt, QtWidgets.QStyle.SC_SliderHandle, self)

        if self.orientation() == QtCore.Qt.Horizontal:
            sliderLength = sr.width()
            sliderMin = gr.x()
            sliderMax = gr.right() - sliderLength + 1
        else:
            sliderLength = sr.height()
            sliderMin = gr.y()
            sliderMax = gr.bottom() - sliderLength + 1;
        pr = pos - sr.center() + sr.topLeft()
        p = pr.x() if self.orientation() == QtCore.Qt.Horizontal else pr.y()
        return QtWidgets.QStyle.sliderValueFromPosition(self.minimum(), self.maximum(), p - sliderMin,
                                               sliderMax - sliderMin, opt.upsideDown)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1492, 873)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 1471, 821))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 1431, 401))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = PlotWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.graphicsView_2 = PlotWidget(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView_2.sizePolicy().hasHeightForWidth())
        self.graphicsView_2.setSizePolicy(sizePolicy)
        self.graphicsView_2.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout.addWidget(self.graphicsView_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    \n"
"}")
        self.pushButton_25.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/speaker-filled-audio-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_25.setIcon(icon)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_2.addWidget(self.pushButton_25, 0, 2, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}\n"
"")
        self.pushButton_23.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_23.setIcon(icon1)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_2.addWidget(self.pushButton_23, 0, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}\n"
"")
        self.pushButton_24.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_24.setIcon(icon2)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_2.addWidget(self.pushButton_24, 0, 1, 1, 1)
        self.horizontalSlider = Slider(self.gridLayoutWidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_2.addWidget(self.horizontalSlider, 0, 3, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(20, 420, 1431, 361))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(0, 20, 1421, 331))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 3, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 3, 1, 1, 1)
        self.E_FlatClarinetGainVerticalSlider = Slider(self.gridLayoutWidget_3)
        self.E_FlatClarinetGainVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.E_FlatClarinetGainVerticalSlider.setObjectName("E_FlatClarinetGainVerticalSlider")
        self.gridLayout_3.addWidget(self.E_FlatClarinetGainVerticalSlider, 1, 2, 1, 1)
        self.PiccoloGainVerticalSlider = Slider(self.gridLayoutWidget_3)
        self.PiccoloGainVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.PiccoloGainVerticalSlider.setObjectName("PiccoloGainVerticalSlider")
        self.gridLayout_3.addWidget(self.PiccoloGainVerticalSlider, 1, 3, 1, 1)
        self.TromboneGainVerticalSlider = Slider(self.gridLayoutWidget_3)
        self.TromboneGainVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.TromboneGainVerticalSlider.setObjectName("TromboneGainVerticalSlider")
        self.gridLayout_3.addWidget(self.TromboneGainVerticalSlider, 1, 1, 1, 1)
        self.ViolaGainVerticalSlider = Slider(self.gridLayoutWidget_3)
        self.ViolaGainVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.ViolaGainVerticalSlider.setObjectName("ViolaGainVerticalSlider")
        self.gridLayout_3.addWidget(self.ViolaGainVerticalSlider, 1, 4, 1, 1)
        self.BassGainVerticalSlider = Slider(self.gridLayoutWidget_3)
        self.BassGainVerticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.BassGainVerticalSlider.setObjectName("BassGainVerticalSlider")
        self.gridLayout_3.addWidget(self.BassGainVerticalSlider, 1, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 0, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 4, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 4, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 1, 1, 1)

        self.BassGainValueTextLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.BassGainValueTextLabel.setObjectName("BassGainValueTextLabel")
        self.gridLayout_3.addWidget(self.BassGainValueTextLabel, 2, 0, 1, 1)

        self.TromboneGainValueTextLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.TromboneGainValueTextLabel.setObjectName("TromboneGainValueTextLabel")
        self.gridLayout_3.addWidget(self.TromboneGainValueTextLabel, 2, 1, 1, 1)

        self.E_FlatClarinetGainValueTextLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.E_FlatClarinetGainValueTextLabel.setObjectName("E_FlatClarinetGainValueTextLabel")
        self.gridLayout_3.addWidget(self.E_FlatClarinetGainValueTextLabel, 2, 2, 1, 1)

        self.PiccoloGainValueTextLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.PiccoloGainValueTextLabel.setObjectName("PiccoloGainValueTextLabel")
        self.gridLayout_3.addWidget(self.PiccoloGainValueTextLabel, 2, 3, 1, 1)

        self.ViolaGainValueTextLabel = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.ViolaGainValueTextLabel.setObjectName("ViolaGainValueTextLabel")
        self.gridLayout_3.addWidget(self.ViolaGainValueTextLabel, 2, 4, 1, 1)

        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("Bass.png"))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 1)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(490, 0, 16, 611))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(1010, 0, 16, 611))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(30, 130, 431, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("R.jpg"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(590, 130, 361, 271))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("PNG.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(1050, 150, 311, 271))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("bongosPNG.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(170, 40, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(630, 30, 231, 81))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(1170, 40, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setGeometry(QtCore.QRect(400, 290, 51, 101))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 290, 51, 101))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 290, 51, 101))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 290, 51, 101))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(160, 290, 51, 101))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setGeometry(QtCore.QRect(100, 290, 51, 101))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 290, 51, 101))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(380, 130, 30, 151))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(320, 130, 28, 151))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(260, 130, 28, 151))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(140, 130, 27, 151))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_12.setGeometry(QtCore.QRect(80, 130, 27, 151))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_12.setText("")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(890, 230, 22, 70))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_13.setText("")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_21.setGeometry(QtCore.QRect(1180, 200, 51, 60))
        self.pushButton_21.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"")
        self.pushButton_21.setText("")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_22.setGeometry(QtCore.QRect(1230, 190, 51, 60))
        self.pushButton_22.setStyleSheet("QPushButton {\n"
"    color: #333;\n"
"    border-radius: 20px;\n"
"    border-style: outset;\n"
"    padding: 5px;\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background: qradialgradient(\n"
"        cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"        radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
"        );\n"
"    }\n"
"")
        self.pushButton_22.setText("")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(850, 220, 25, 90))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(800, 220, 30, 95))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_15.setText("")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(760, 220, 26, 99))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_16.setText("")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(720, 220, 23, 100))
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_17.setText("")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(680, 220, 23, 100))
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_18.setText("")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(630, 210, 26, 114))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_20.setGeometry(QtCore.QRect(600, 210, 16, 119))
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
" background-color: rgb(229,229,229);\n"
"}")
        self.pushButton_20.setText("")
        self.pushButton_20.setObjectName("pushButton_20")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1492, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Song Graph"))
        self.label_8.setText(_translate("MainWindow", "Spectrogram"))
        self.groupBox.setTitle(_translate("MainWindow", "Instrument Emphasizer"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "20,000 Hz"))
        self.label_14.setText(_translate("MainWindow", "Bass"))
        self.label_18.setText(_translate("MainWindow", "Viola"))
        self.label_17.setText(_translate("MainWindow", "Piccolo"))
        self.label_19.setText(_translate("MainWindow", "128 Hz"))
        self.label_15.setText(_translate("MainWindow", "Trombone"))
        self.label_16.setText(_translate("MainWindow", "E-Flat Clarinet"))
        self.label_22.setText(_translate("MainWindow", "2000 Hz"))
        self.label_21.setText(_translate("MainWindow", "1000 Hz"))
        self.label_20.setText(_translate("MainWindow", "550 Hz"))
        self.BassGainValueTextLabel.setText(_translate("MainWindow", "1x"))
        self.TromboneGainValueTextLabel.setText(_translate("MainWindow", "1x"))
        self.E_FlatClarinetGainValueTextLabel.setText(_translate("MainWindow", "1x"))
        self.PiccoloGainValueTextLabel.setText(_translate("MainWindow", "1x"))
        self.ViolaGainValueTextLabel.setText(_translate("MainWindow", "1x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.label_4.setText(_translate("MainWindow", "Piano"))
        self.label_5.setText(_translate("MainWindow", "Xylophone"))
        self.label_6.setText(_translate("MainWindow", "Bongos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
from pyqtgraph import PlotWidget
# import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
